### PR TITLE
Implement try_normalized for vectors

### PR DESCRIPTION
**Pull request by timokoesters**
This is fairly useful when you don't want your code to generate a lot of NaNs

### CODE REVIEW

**Comment by yoanlcq** [comment]
Hi, thanks for the PR.

Your code is OK as-is, there are a few tiny things that should be addressed before merging.

First, the comparison should use `ApproxEq` for consistency with e.g `is_normalized()`. While we're at it, it would be nice to provide something like `is_approx_zero()`, similar to `is_normalized()`, but you could then use it in `try_normalized()`.

The `Some(self / self.magnitude())` line should be `Some(self.normalized())`. It's the exact same, but more logical IMO.

The doc comment for `try_normalized()` should mention that approximate equality is used (pretty much like `is_normalized()` does).

Finally, feel free to add yourself to the list of authors in Cargo.toml and README.md!

**Comment by timokoesters** [comment]
@yoanlcq Thanks for the review, the code should be good now.

**Comment by yoanlcq** [comment]
Thanks!

**Comment by timokoesters** [comment]
@yoanlcq When will that update land on crates.io?

**Comment by yoanlcq** [comment]
Right now! :) Sorry for the wait.

**Pull request merged**
