### PR TITLE
Fix compatibility with latest nightly toolchain version

### PR DESCRIPTION
**Pull request by crabm4n**
Platform intrinsics were removed and are replaced with `core_intrinsics` (now accessible via `std::intrinsics::simd`).

This is a breaking change as the `simd_llvm` and `simd_traits` which were publicly exported are removed.

### CODE REVIEW

**Comment by xMAC94x** [comment]
Hi @yoanlcq  this MR is necessary for the veloren team to update the rust toolchain and newer toolschains had become incompatible with vek . do you have some time for a review? 
best regards,
Marcel

**Comment by yoanlcq** [comment]
Hey guy, sorry for the delay! It's been a long 5-day week-end here in France.

This looks good to me. I was about to ask whether there was any way to be backwards compatible with prior compiler versions, but I guess there's no point: SIMD was always unstable and required explicit opt-in by using Nightly and enabling the `platform_intrinsics` feature. Plus, previous versions of `vek` are always available.

Thank you @crabm4n for your effort, I very much appreciate it.
You have waited long enough, so I'll merge this right now, then push a new version. If you'd like to add yourself to the list of contributors (README + Cargo.toml) then feel free to do so even in a separate PR.

**Comment by maxicarlos08** [comment]
Thank you and no worries for the delay ;D

**Comment by xMAC94x** [comment]
Thank you very much. No worries, we all have a personal live that matter first. Waiting a few days is absolutely no issue :) 
Hope you enjoyed the long and sunny weekend :)

**Pull request merged**
