### PR TITLE
Added point projection (and distance_to_point) to Aabr and Aabb

### PR DESCRIPTION
**Pull request by zesterer**
I figured that since the implementation is quite simple it didn't warrant any tests.

### CODE REVIEW

**Comment by yoanlcq** [comment]
Hi, the implementation is great and I am OK with it as it is!  

There are some really minor points I'd like to raise before merging :

- While `projected_point` is an appropriate name, mathematically speaking, I'm wondering if there's a more "discoverable" name we could use.
  For instance, some googling seems to reveal that people tend to talk about "closest point to AABB" and almost nobody talks about "project point on AABB", even though both are effectively what we're doing.
  So I'm just wondering if we should name it `closest_point()` instead.
- Couldn't the implementation of `projected_point()` be rewritten more simply as `p.clamped(self.min, self.max)` ? (that shouldn't require changing the trait bounds)

**Comment by yoanlcq** [comment]
Meh, I just realized that what you did is consistent with the `LineSegment::projected_point()` functions we already have... Consistency should win I guess.  
Maybe `closest_point()` could be added as an alias but then it would introduce redundancy and possibly unnecessary confusion for users... So that's probably a bad idea. `projected_point` is good.

**Comment by zesterer** [comment]
Yeah, I considered this but I figured that consistency is more appropriate. Regardless, I think the doc comment should help out users.

> Couldn't the implementation of projected_point() be rewritten more simply as p.clamped(self.min, self.max)?

You're totally right, I didn't consider that. I'll change that now.

**Comment by yoanlcq** [comment]
Great! Let's merge, and I'll publish a new version with this change right away. Thanks.

**Pull request merged**
