### PR TITLE
Implement From<Aabb> for Aabr

### PR DESCRIPTION
**Pull request by zesterer**
Apologies, my editor seems to have removed trailing whitespace. I hope that's ok.

### CODE REVIEW

**Comment by yoanlcq** [comment]
Sure! No problem. This reminds me that I should get rid of training whitespace in all files, at some point. :smile: 

This warrants a version increase, but at the same time it's quite a small change (and there may be more? idk), so I'm thinking to myself I might as well make it worth by revisiting open issues and fixing/improving what I can, over the weekend.  
In short I'd rather wait a tiny bit before uploading a new version to crates.io, if you're OK with this!

**Comment by zesterer** [comment]
Sure, that's fine!

**Comment by yoanlcq** [comment]
@zesterer By the way I should add you to the list of authors in Cargo.toml and the README. How would you like to appear in Cargo.toml, [given the expected format](https://doc.rust-lang.org/cargo/reference/manifest.html) ?

**Comment by zesterer** [comment]
@yoanlcq `Joshua Barretto <joshua.s.barretto@gmail.com>` is fine. Thank you!

**Pull request merged**
