### PR TITLE
Implement ``bytemuck`` traits for other common types

### PR DESCRIPTION
**Pull request by jedjoud10**
Implemented ``Zeroable`` and ``Pod`` for all ``Vec<T>`` types and their variants (simd and repr_c), ``Mat4<T>``s, and for ``Quaternion``

### CODE REVIEW

**Comment by jedjoud10** [comment]
Hm seems like the CI itself fails. Pretty odd

**Comment by yoanlcq** [comment]
Hey, sorry for the delay, thanks for submitting this PR, it looks good. I have no idea what caused the appveyor failure even after seeing the logs.

What I'm going to do is merge this regardless, compile locally, and if it works I'll push a new version with this change.

**Comment by yoanlcq** [comment]
Done, available in 0.16.0
Thanks again!

**Comment by jedjoud10** [comment]
Ah shoot it doesn't compile with the ``bytemuck`` feature. Such simple mistakes as well. Sorry so much about that, I should've tested and not relied on CI.

**Comment by yoanlcq** [comment]
No problem, I'll refer #94 from here

**Pull request merged**
